theme: jekyll-theme-minimal
title: ""
description: "LitSift: Seamlessly search, sift, and export results from Semantic Scholar to BibTeX/CSV"
logo: /LitSift.ico
show_downloads: true
github:
  zip_url: https://github.com/ekjaisal/LitSift/archive/refs/tags/v1.0.1.zip
  exe_url: https://github.com/ekjaisal/LitSift/releases/download/v1.0.1/LitSift_v1.0.1_Installer.exe